name: dental_seller
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter_bloc: ^9.1.1
  get_it: ^9.2.0
  shared_preferences: ^2.5.4
  freezed_annotation: ^3.1.0
  bot_toast: ^4.1.3
  go_router: ^17.0.1
  gap: ^3.0.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  flutter_secure_storage: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0
  build_runner: ^2.10.5
  freezed: ^3.2.4
  json_serializable: ^6.11.4


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/img/
    - assets/fonts/

  fonts:
    - family: Nunito-Medium
      fonts:
        - asset: assets/fonts/nunito/Nunito-Medium.ttf

    - family: Nunito-Regular
      fonts:
        - asset: assets/fonts/nunito/Nunito-Regular.ttf

    - family: Nunito-Bold
      fonts:
        - asset: assets/fonts/nunito/Nunito-Bold.ttf

    - family: Nunito-SemiBold
      fonts:
        - asset: assets/fonts/nunito/Nunito-SemiBold.ttf